import type { SiteContent } from './types';

export const defaultContent: SiteContent = {
  heroTitle: 'STRUCTURED ENGLISH LAB // PEARSON x STEAM',
  heroSubtitle: 'A bilingual engineering lab notebook for structured English acquisition — built on Pearson curriculum and STEAM methodology.',
  introTitle: 'Meet your instructor',
  introBody: 'I am Miss Malak. I designed TOLERANCE LAB to bridge structured English learning with hands-on engineering. Every unit is anchored in Pearson curriculum, and every lab is an experiment — because language, like engineering, is built by doing. This platform is your lab notebook: edit it, track your progress, and make each experiment your own.',
  introName: 'Eng. Malak',
  introRole: 'Curriculum Architect & STEAM Instructor',
  unitsTitle: 'Pearson Units',
  unitsSubtitle: 'Eight structured units from the Pearson English curriculum. Each unit builds vocabulary, grammar, and communicative competence.',
  archiveTitle: 'STEAM Lab Archive',
  archiveSubtitle: 'A growing archive of hands-on experiments. Each lab connects a Pearson unit to a real-world STEAM challenge.',
  trackerTitle: 'My Lab Tracker',
  trackerSubtitle: 'Track your progress through the archive. Mark labs complete, add your experiment photos, and keep your notes.',
  footerText: '© TOLERANCE LAB by Eng Malak',
  units: [
    {
      id: 'unit-01',
      number: '01',
      title: 'Jobs',
      concept: 'Career aspirations, job types',
      subtitle: 'Career aspirations, job types',
      lessons: [
        { id: 'l01', number: '01', category: 'Vocabulary', title: 'Jobs', link: 'https://tubular-salmiakki-dc0ccf.netlify.app', vocabulary: ['architect', 'athlete', 'dentist', 'electrician', 'mechanic', 'nurse', 'paramedic', 'photographer', 'scientist', 'waiter', 'writer'] },
        { id: 'l02', number: '02', category: 'Grammar', title: 'I want to be ... / He wants to be ...', link: 'https://tubular-salmiakki-dc0ccf.netlify.app' },
        { id: 'l04', number: '04', category: 'Grammar', title: 'Questions with do/does', link: 'https://splendorous-figolla-be4055.netlify.app' },
        { id: 'l05', number: '05', category: 'Reading', title: 'Story 1', link: '#' },
        { id: 'l06', number: '06', category: 'Writing', title: 'My future job and life', link: '#' },
        { id: 'l07', number: '07', category: 'Phonics', title: 'ou / ow', link: '#' },
        { id: 'l08', number: '08', category: 'Writing', title: 'Second writing task', link: '#' },
        { id: 'l09', number: '09', category: 'Reading', title: 'Story 2', link: '#' },
      ],
    },
    {
      id: 'unit-02',
      number: '02',
      title: 'Feelings',
      concept: 'Emotions and how we express them',
      subtitle: 'Emotions and how we express them',
      lessons: [],
    },
    {
      id: 'unit-03',
      number: '03',
      title: 'Action!',
      concept: 'Verbs, commands, and doing things',
      subtitle: 'Verbs, commands, and doing things',
      lessons: [],
    },
    {
      id: 'unit-04',
      number: '04',
      title: 'Friends',
      concept: 'Relationships and social language',
      subtitle: 'Relationships and social language',
      lessons: [],
    },
    {
      id: 'unit-05',
      number: '05',
      title: 'Daily life',
      concept: 'Routines, habits, and everyday activities',
      subtitle: 'Routines, habits, and everyday activities',
      lessons: [],
    },
    {
      id: 'unit-06',
      number: '06',
      title: 'Leisure activities',
      concept: 'Hobbies, sports, and free time',
      subtitle: 'Hobbies, sports, and free time',
      lessons: [],
    },
    {
      id: 'unit-07',
      number: '07',
      title: 'Shopping',
      concept: 'Money, prices, and transactions',
      subtitle: 'Money, prices, and transactions',
      lessons: [],
    },
    {
      id: 'unit-08',
      number: '08',
      title: 'The natural world',
      concept: 'Animals, plants, and the environment',
      subtitle: 'Animals, plants, and the environment',
      lessons: [],
    },
  ],
  labs: [
    {
      id: 'lab001',
      number: '001',
      title: 'Density Tower',
      tag: 'SCIENCE',
      subtitle: 'Layering liquids to observe density gradients and buoyancy.',
      videoUrl: '',
      materials: [
        'Honey (100 mL)',
        'Corn syrup (100 mL)',
        'Dish soap (100 mL)',
        'Water (100 mL, colored)',
        'Vegetable oil (100 mL)',
        'Rubbing alcohol (100 mL, colored)',
        'Clear tall glass',
      ],
      tools: ['Graduated cylinder', 'Food coloring', 'Dropper', 'Funnel'],
      protocol: [
        {
          title: 'Preparation',
          body: 'Clear your workspace. Put on safety goggles. Lay out all six liquids in the order you will pour them, from most to least dense.',
        },
        {
          title: 'Layering',
          body: 'Pour honey first, slowly, to the bottom. Wait 30 seconds. Add corn syrup using the funnel against the glass wall to avoid mixing. Repeat with dish soap.',
        },
        {
          title: 'Observation',
          body: 'Add water, then oil, then alcohol — each poured slowly against the wall. Observe and sketch the layers. Record which liquids stay separate and why.',
        },
        {
          title: 'Analysis',
          body: 'Drop a small bead, a grape, and a coin into the tower. Record where each object settles. Write a paragraph explaining density using your observations.',
        },
      ],
      vocabulary: [
        { term: 'Density', definition: 'Mass per unit volume of a substance.' },
        { term: 'Buoyancy', definition: 'The upward force a fluid exerts on an object immersed in it.' },
        { term: 'Immiscible', definition: 'Two liquids that do not mix or blend together.' },
        { term: 'Gradient', definition: 'A gradual change in a property across a distance.' },
      ],
    },
    {
      id: 'lab002',
      number: '002',
      title: 'Paper Circuit',
      tag: 'TECH',
      subtitle: 'Building a working circuit using copper tape, a battery, and an LED.',
      videoUrl: '',
      materials: [
        'Cardstock (A4)',
        'Copper conductive tape (2 m)',
        'Coin cell battery (CR2032)',
        'LED (red, 3 mm)',
        'Binder clip',
      ],
      tools: ['Scissors', 'Pencil', 'Ruler', 'Tape (regular)'],
      protocol: [
        {
          title: 'Design',
          body: 'Sketch your circuit path on the cardstock. Plan where the battery, LED, and copper tape will go. The path must form a complete loop from battery to LED and back.',
        },
        {
          title: 'Build',
          body: 'Lay copper tape along your sketched path. Press firmly to ensure continuity. Place the LED leads through small slits, one on each side of the tape path.',
        },
        {
          title: 'Power',
          body: 'Place the coin cell battery on the tape. Use the binder clip to press the tape against both battery terminals. Observe the LED.',
        },
        {
          title: 'Troubleshoot',
          body: 'If the LED does not light, check polarity, tape continuity, and battery orientation. Document each fix you try.',
        },
      ],
      vocabulary: [
        { term: 'Circuit', definition: 'A closed path through which electric current flows.' },
        { term: 'Conductor', definition: 'A material that allows electric current to pass easily.' },
        { term: 'Polarity', definition: 'The direction of positive and negative charge in a circuit.' },
        { term: 'Continuity', definition: 'An unbroken path for current to follow.' },
      ],
    },
    {
      id: 'lab003',
      number: '003',
      title: 'Spaghetti Bridge',
      tag: 'ENGINEERING',
      subtitle: 'Designing and load-testing a truss bridge from dry pasta.',
      videoUrl: '',
      materials: [
        'Dry spaghetti (200 g)',
        'Hot glue gun & sticks',
        'Cardboard base (30×20 cm)',
        'String (50 cm)',
      ],
      tools: ['Ruler', 'Pencil', 'Scissors', 'Small weights (coins or washers)'],
      protocol: [
        {
          title: 'Plan',
          body: 'Draw a truss bridge design on paper. Decide on triangle or Warren truss. Calculate how many spaghetti members you need and their lengths.',
        },
        {
          title: 'Construct',
          body: 'Cut spaghetti to measured lengths. Glue joints carefully — triangles are strongest. Build two identical truss sides, then connect them with cross-members.',
        },
        {
          title: 'Test',
          body: 'Place the bridge between two desks 20 cm apart. Hang a string from the center and add weights one at a time. Record the load at first crack and at failure.',
        },
        {
          title: 'Reflect',
          body: 'Calculate the strength-to-weight ratio. Write a short report: what failed first, why, and how you would redesign it.',
        },
      ],
      vocabulary: [
        { term: 'Truss', definition: 'A structure of triangles designed to distribute load.' },
        { term: 'Tension', definition: 'A pulling force that stretches a member.' },
        { term: 'Compression', definition: 'A pushing force that shortens a member.' },
        { term: 'Load', definition: 'The weight or force a structure must support.' },
      ],
    },
    {
      id: 'lab004',
      number: '004',
      title: 'Solar Oven',
      tag: 'SCIENCE',
      subtitle: 'Harnessing solar energy to melt chocolate using a reflective box.',
      videoUrl: '',
      materials: [
        'Pizza box (large)',
        'Aluminum foil (1 m²)',
        'Plastic wrap',
        'Black construction paper',
        'Chocolate squares',
        'Tape',
      ],
      tools: ['Scissors', 'Ruler', 'Thermometer', 'Pencil'],
      protocol: [
        {
          title: 'Build',
          body: 'Cut a flap in the pizza box lid. Line the flap inside with aluminum foil. Line the box bottom with black paper to absorb heat.',
        },
        {
          title: 'Insulate',
          body: 'Stretch plastic wrap across the opening under the flap to create a greenhouse seal. Tape edges airtight.',
        },
        {
          title: 'Cook',
          body: 'Place chocolate on the black paper. Angle the foil flap toward the sun. Record temperature every 5 minutes for 30 minutes.',
        },
        {
          title: 'Report',
          body: 'Graph temperature over time. Explain how reflection, absorption, and insulation work together in your oven.',
        },
      ],
      vocabulary: [
        { term: 'Reflection', definition: 'Light bouncing off a surface without being absorbed.' },
        { term: 'Absorption', definition: 'Energy taken in by a material and converted to heat.' },
        { term: 'Insulation', definition: 'A barrier that reduces heat transfer.' },
        { term: 'Greenhouse effect', definition: 'Trapping heat inside a transparent enclosure.' },
      ],
    },
    {
      id: 'lab005',
      number: '005',
      title: 'Wind-Powered Lift',
      tag: 'ENGINEERING',
      subtitle: 'Constructing a wind turbine that lifts a small load.',
      videoUrl: '',
      materials: [
        'Cardboard (A4)',
        'Wooden skewers (4)',
        'String (1 m)',
        'Paper cup (small)',
        'Coins (for load)',
        'Fan (as wind source)',
      ],
      tools: ['Scissors', 'Hole punch', 'Ruler', 'Pencil'],
      protocol: [
        {
          title: 'Blade Design',
          body: 'Cut 4–6 blades from cardboard. Experiment with different shapes and angles. Attach blades to a skewer axle.',
        },
        {
          title: 'Assemble',
          body: 'Mount the axle in a cardboard frame. Attach a string with a paper cup to the axle so rotation winds the string.',
        },
        {
          title: 'Test',
          body: 'Place the turbine in front of the fan. Add coins to the cup one at a time. Record how many coins it can lift.',
        },
        {
          title: 'Iterate',
          body: 'Change blade angle or number. Re-test. Write which configuration produced the most lift and why.',
        },
      ],
      vocabulary: [
        { term: 'Turbine', definition: 'A machine that converts fluid energy into rotation.' },
        { term: 'Torque', definition: 'A rotational force around an axis.' },
        { term: 'Pitch', definition: 'The angle of a blade relative to the wind.' },
        { term: 'Efficiency', definition: 'Useful output divided by total input energy.' },
      ],
    },
    {
      id: 'lab006',
      number: '006',
      title: 'Water Filtration',
      tag: 'SCIENCE',
      subtitle: 'Engineering a multi-layer filter to clean muddy water.',
      videoUrl: '',
      materials: [
        'Plastic bottle (2 L, cut in half)',
        'Cotton balls',
        'Activated charcoal',
        'Sand (fine)',
        'Gravel',
        'Muddy water (prepared)',
      ],
      tools: ['Scissors', 'Coffee filter', 'Tweezers', 'Two clear cups'],
      protocol: [
        {
          title: 'Layer',
          body: 'Invert the bottle top into the bottom half. Layer materials in order: cotton, charcoal, sand, gravel. Press each layer flat.',
        },
        {
          title: 'Filter',
          body: 'Pour muddy water slowly into the top. Collect the filtered water in a clear cup below.',
        },
        {
          title: 'Compare',
          body: 'Place the original muddy water and the filtered water side by side. Observe color, clarity, and any particles.',
        },
        {
          title: 'Evaluate',
          body: 'Discuss what each layer removed. Write whether the filtered water is safe to drink and why or why not.',
        },
      ],
      vocabulary: [
        { term: 'Filtration', definition: 'Passing a mixture through a medium to remove solids.' },
        { term: 'Permeability', definition: 'How easily fluid flows through a material.' },
        { term: 'Adsorption', definition: 'Particles sticking to a surface, as with charcoal.' },
        { term: 'Potable', definition: 'Safe and suitable for drinking.' },
      ],
    },
  ],
};
